const mongoose=require("mongoose");
const notificationSchema=new mongoose.Schema({
    patient:
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:"Patient",
        required:true
    },
    doctor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    message:
    {
        type:String,
        required:true
    },
    date:
    {
        type:Date,
        default:Date.now
    },
    read:
    {
        type:Boolean,
        default:false
    }
});
module.exports=mongoose.model("Notification",notificationSchema);